# Generated by Django 4.0.1 on 2022-02-03 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_student_active_student_birthday_student_create_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
