from core.serializers.student_registration_serializer import StudentRegistrationSerializer
from core.serializers.admin_registration_serializer import AdminRegistrationSerializer
from core.serializers.doctor_registration_serializer import DoctorRegistrationSerializer
from core.serializers.instructor_registration_serializer import InstructorRegistrationSerializer
