from api.serializers.student_serializer import StudentSerializer
from api.serializers.admin_serializer import AdminSerializer
from api.serializers.doctor_serializer import DoctorSerializer
from api.serializers.instructor_serializer import InstructorSerializer
from api.serializers.student_schedule_serializer import StudentScheduleSerializer
from api.serializers.schedule_config_serializer import ScheduleConfigSerializer
from api.serializers.doctor_schedule_serializer import DoctorScheduleSerializer
